services:
  - type: worker
    name: telegram-summarizer-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-3.5-turbo
      - key: MESSAGE_LIMIT
        value: 75
      - key: MAX_MESSAGE_AGE_HOURS
        value: 24
